<?php

use HnhDigital\LaravelFrontendAssets as Assets;

return [
    'Animate'                 => [Assets\Animate::class, '3.5.2'],
    'Autosize'                => [Assets\Autosize::class, '4.0.0'],
    'Backbone'                => [Assets\Backbone::class, '1.3.3'],
    'BackboneMarionette'      => [Assets\BackboneMarionette::class, '3.5.0'],
    'BackboneLocalPersist'    => [Assets\BackboneLocalPersist::class, '1.1.1'],
    'Bootstrap'               => [Assets\Bootstrap::class, '4.0.0'],
    'ChartJs'                 => [Assets\ChartJs::class, '2.7.1'],
    'PasswordComplexifyInput' => [Assets\PasswordComplexifyInput::class, '0.5.1'],
    'DateInput'               => [Assets\DateInput::class, '1.6.1'],
    'DiffMatchPatch'          => [false, '20121119'],
    'Dropzone'                => [Assets\Dropzone::class, '4.3.0'],
    'ElementTransitions'      => [Assets\ElementTransitions::class],
    'FontAwesome'             => [Assets\FontAwesome::class, '5.0.1'],
    'FlagIcon'                => [Assets\FlagIcon::class],
    'Flot'                    => [Assets\Flot::class, '0.8.3'],
    'FlotTooltop'             => [Assets\FlotTooltop::class, '0.8.7'],
    'GoogleMaps'              => [Assets\GoogleMaps::class],
    'IcheckInput'             => [Assets\IcheckInput::class, '1.0.2'],
    'Jquery'                  => [Assets\Jquery::class, '3.3.1'],
    'JqueryUi'                => [Assets\JqueryUi::class, '1.12.0'],
    'JqueryUiTheme'           => [false, 'smoothness'],
    'Ladda'                   => [Assets\Ladda::class, '1.0.0'],
    'MetisMenu'               => [Assets\MetisMenu::class, '2.5.2'],
    'MiniColors'              => [Assets\MiniColors::class, '2.2.6'],
    'MultiEmailInput'         => [Assets\MultiEmailInput::class, '0.0.2'],
    'Pace'                    => [Assets\Pace::class, '1.0.2'],
    'Popper'                  => [Assets\Popper::class, '1.12.6'],
    'Redactor'                => [Assets\Redactor::class],
    'Slimscroll'              => [Assets\Slimscroll::class, '1.3.7'],
    'Sparkline'               => [Assets\Sparkline::class, '2.1.2'],
    'TextDiff'                => [Assets\TextDiff::class, '1.0.4'],
    'Toastr'                  => [Assets\Toastr::class, 'latest'],
    'Select2'                 => [Assets\Select2::class, '4.0.3'],
    'Slick'                   => [Assets\Slick::class, '1.8.1'],
    'Steps'                   => [Assets\Steps::class, '1.1.0'],
    'StickyTabs'              => [Assets\StickyTabs::class, '1.0.3'],
    'Stripe'                  => [Assets\Stripe::class, '3'],
    'TagsInput'               => [Assets\TagsInput::class, '0.8.0'],
    'TimeInput'               => [Assets\TimeInput::class, '1.11.10'],
    'Translations'            => [Assets\Translations::class],
    'Underscore'              => [Assets\Underscore::class, '1.8.3'],
    'ValidateInput'           => [Assets\ValidateInput::class, '1.15.0'],
    'Vectormap'               => [Assets\Vectormap::class, '2.0.2'],
    'VideoJs'                 => [Assets\VideoJs::class, '6.4.0'],
    'Zip'                     => [Assets\Zip::class, '2.6.1'],
];
