<?php

return [
    'AutoInit'                => [Bluora\LaravelResourcesLoader\Assets\AutoInit::class],
    'Bootstrap'               => [Bluora\LaravelResourcesLoader\Assets\Bootstrap::class, '3.3.6'],
    'PasswordComplexifyInput' => [Bluora\LaravelResourcesLoader\Assets\PasswordComplexifyInput::class, '0.5.1'],
    'DateInput'               => [Bluora\LaravelResourcesLoader\Assets\DateInput::class, '1.6.1'],
    'DiffMatchPatch'          => [false, '20121119'],
    'Dropzone'                => [Bluora\LaravelResourcesLoader\Assets\Dropzone::class, '4.3.0'],
    'FontAwesome'             => [Bluora\LaravelResourcesLoader\Assets\FontAwesome::class, '5.0.1'],
    'FlagIcon'                => [Bluora\LaravelResourcesLoader\Assets\FlagIcon::class],
    'Flot'                    => [Bluora\LaravelResourcesLoader\Assets\Flot::class, '0.8.3'],
    'FlotTooltop'             => [Bluora\LaravelResourcesLoader\Assets\FlotTooltop::class, '0.8.7'],
    'GoogleMaps'              => [Bluora\LaravelResourcesLoader\Assets\GoogleMaps::class],
    'IcheckInput'             => [Bluora\LaravelResourcesLoader\Assets\IcheckInput::class, '1.0.2'],
    'Jquery'                  => [Bluora\LaravelResourcesLoader\Assets\Jquery::class, '2.2.4'],
    'JqueryUi'                => [Bluora\LaravelResourcesLoader\Assets\JqueryUi::class, '1.12.0'],
    'JqueryUiTheme'           => [false, 'smoothness'],
    'Ladda'                   => [Bluora\LaravelResourcesLoader\Assets\Ladda::class, '1.0.0'],
    'MetisMenu'               => [Bluora\LaravelResourcesLoader\Assets\MetisMenu::class, '2.5.2'],
    'MultiEmailInput'         => [Bluora\LaravelResourcesLoader\Assets\MultiEmailInput::class, '0.0.2'],
    'Pace'                    => [Bluora\LaravelResourcesLoader\Assets\Pace::class, '1.0.2'],
    'Redactor'                => [Bluora\LaravelResourcesLoader\Assets\Redactor::class],
    'Slimscroll'              => [Bluora\LaravelResourcesLoader\Assets\Slimscroll::class, '1.3.7'],
    'Sparkline'               => [Bluora\LaravelResourcesLoader\Assets\Sparkline::class, '2.1.2'],
    'TextDiff'                => [Bluora\LaravelResourcesLoader\Assets\TextDiff::class, '1.0.4'],
    'Toastr'                  => [Bluora\LaravelResourcesLoader\Assets\Toastr::class, 'latest'],
    'Select2'                 => [Bluora\LaravelResourcesLoader\Assets\Select2::class, '4.0.3'],
    'Steps'                   => [Bluora\LaravelResourcesLoader\Assets\Steps::class, '1.1.0'],
    'StickyTabs'              => [Bluora\LaravelResourcesLoader\Assets\StickyTabs::class, '1.0.3'],
    'TagsInput'               => [Bluora\LaravelResourcesLoader\Assets\TagsInput::class, '0.8.0'],
    'TimeInput'               => [Bluora\LaravelResourcesLoader\Assets\TimeInput::class, '1.11.10'],
    'ValidateInput'           => [Bluora\LaravelResourcesLoader\Assets\ValidateInput::class, '1.15.0'],
    'Vectormap'               => [Bluora\LaravelResourcesLoader\Assets\Vectormap::class, '2.0.2'],
    'Zip'                     => [Bluora\LaravelResourcesLoader\Assets\Zip::class, '2.6.1'],
];
